export enum Theme {
  LIGHT = 'light',
  DARK = 'dark',
  DRACULA = 'dracula',
  NORD = 'nord',
  MONOKAI = 'monokai',
  SOLARIZED = 'solarized',
  SOLARIZED_DARK = 'solarized-dark',
  SOLARIZED_LIGHT = 'solarized-light',
  GITHUB = 'github',
  GITHUB_DARK = 'github-dark',
  ONE = 'one',
  ONE_DARK = 'one-dark',
  MATERIAL = 'material',
  HIGH_CONTRAST = 'high-contrast',
  SEPIA = 'sepia',
  SYNTHWAVE = 'synthwave',
  FOREST = 'forest',
  OCEAN = 'ocean',
  AUTO = 'auto',
}
